In [1]:
import pandas as pd

In [2]:
seed=1234

In [3]:
#Abro el archivo con la informacion
#Normalizada
#data = pd.read_csv('attritionDataWithDummyVarsAndNorm.csv')
#Sin normalizar
data = pd.read_csv('attritionDataWithDummyVars.csv')

### Data split

In [4]:
y=data['Dummy_Attrition_Yes']
x=data.drop(['Dummy_Attrition_Yes'], axis=1)

In [5]:
x.head()

Age  DailyRate  DistanceFromHome  Education  EmployeeCount  EmployeeNumber  \
0   41       1102                 1          2              1               1   
1   49        279                 8          1              1               2   
2   37       1373                 2          2              1               4   
3   33       1392                 3          4              1               5   
4   27        591                 2          1              1               7   

   EnvironmentSatisfaction  HourlyRate  JobInvolvement  JobLevel  ...  \
0                        2          94               3         2  ...   
1                        3          61               2         2  ...   
2                        4          92               2         1  ...   
3                        4          56               3         1  ...   
4                        1          40               3         1  ...   

   Dummy_JobRole_Research Director  Dummy_JobRole_Research Scientist  \
0                                0                                 0   
1                                0                                 1   
2                                0                                 0   
3                                0                                 1   
4                                0                                 0   

   Dummy_JobRole_Sales Executive  Dummy_JobRole_Sales Representative  \
0                              1                                   0   
1                              0                                   0   
2                              0                                   0   
3                              0                                   0   
4                              0                                   0   

   Dummy_MaritalStatus_Divorced  Dummy_MaritalStatus_Married  \
0                             0                            0   
1                             0                            1   
2                             0                            0   
3                             0                            1   
4                             0                            1   

   Dummy_MaritalStatus_Single  Dummy_Over18_Y  Dummy_OverTime_No  \
0                           1               1                  0   
1                           0               1                  1   
2                           1               1                  0   
3                           0               1                  0   
4                           0               1                  1   

   Dummy_OverTime_Yes  
0                   1  
1                   0  
2                   1  
3                   1  
4                   0  

[5 rows x 55 columns]

In [6]:
#from sklearn import preprocessing
#Xn = preprocessing.StandardScaler().fit(x).transform(x.astype(float))
#Xn[0:5]

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify=y, random_state=seed )

In [8]:
y_test=y_test.reset_index(drop=True)

In [9]:
### Single decision tree

In [10]:
dt = pd.read_csv('AttrttionResultsDT')

In [11]:
### K neig

In [12]:
kNeigh = pd.read_csv('AttrttionResultsKneigh')

In [13]:
### LGbm

In [14]:
lgbm = pd.read_csv('AttrttionResultsLGBM')

In [15]:
### Logistic regresion

In [16]:
lr = pd.read_csv('AttrttionResultsLogReg')

In [17]:
### Random forest

In [18]:
rf = pd.read_csv('AttrttionResultsRF')

In [19]:
### Support Vector Machine

In [20]:
svm= pd.read_csv('AttrttionResultsSVM')

In [21]:
### XGboost

In [22]:
xgb= pd.read_csv('AttrttionResultsXGboost')

### Addition

In [23]:
add=dt['predict']+kNeigh['predict']+lgbm['predict']+lr['predict']+rf['predict']+svm['predict']+xgb['predict']

In [24]:
import numpy as np
predAdd=np.where(add >= 1, 1, add)

In [25]:
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, predAdd)
print(confusionMatrix)

[[312  58]
 [ 28  43]]


In [26]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, predAdd)

0.7244385230300724

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predAdd))

              precision    recall  f1-score   support

           0       0.92      0.84      0.88       370
           1       0.43      0.61      0.50        71

    accuracy                           0.80       441
   macro avg       0.67      0.72      0.69       441
weighted avg       0.84      0.80      0.82       441



### Average

In [28]:
n=7
predAvg=np.round(add / n).astype(int)

In [29]:
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, predAvg)
print(confusionMatrix)

[[370   0]
 [ 58  13]]


In [30]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, predAvg)

0.5915492957746479

In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predAvg))

              precision    recall  f1-score   support

           0       0.86      1.00      0.93       370
           1       1.00      0.18      0.31        71

    accuracy                           0.87       441
   macro avg       0.93      0.59      0.62       441
weighted avg       0.89      0.87      0.83       441



### AND operation

In [32]:
predMul=dt['predict']*kNeigh['predict']*lgbm['predict']*lr['predict']*rf['predict']*svm['predict']*xgb['predict']

In [33]:
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, predMul)
print(confusionMatrix)

[[370   0]
 [ 71   0]]


### Log Reg

In [34]:
Mydata=pd.DataFrame()
Mydata['Dummy_Attrition_Yes']=y_test

In [35]:
Mydata['dt']=dt['predict']
Mydata['kNeigh']=kNeigh['predict']
Mydata['lgbm']=lgbm['predict']
Mydata['lr']=lr['predict']
Mydata['rf']=rf['predict']
Mydata['svm']=svm['predict']
Mydata['xgb']=xgb['predict']



In [36]:
Mydata.head()

Dummy_Attrition_Yes  dt  kNeigh  lgbm  lr  rf  svm  xgb
0                    0   0       0     1   0   0    0    0
1                    0   0       0     0   0   0    0    0
2                    0   0       0     0   0   1    0    0
3                    0   0       0     0   0   0    0    0
4                    0   0       0     0   0   0    0    0

In [37]:
Mydata.to_csv('ensamble.csv', index=False) 